config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "pages#home"

  resources :cars, only: [ :index, :show ] do
    resources :reviews, only: :create
    resources :favourites, only: [ :create ]
  end

  resources :favourites, only: [ :index, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites

  validates :brand, :model, :fuel, presence: :true
  validates :year, presence: :true, numericality: { only_integer: true }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars

  validates :nickname, uniqueness: true, presence: :true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car

  validates :comment, presence: :true
  validates :rating, numericality: { only_integer: true }, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def create
    @favourite = Favourite.new
    @car = Car.find(params[:car_id])
    @favourite.car = @car

    if @favourite.save
      redirect_to car_path(@car)
      # change icon to red
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @favourites = Favourite.all
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path(@favourite), status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @car = Car.find(params[:car_id])
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<div class="banner" style="background-image: url(<%= asset_path 'banner.jpg' %>)">
  <div class="text-start">
    <h1>Gone In 60 Seconds</h1>
  </div>
</div>



<ul class="listing">
  <% @cars.each do |car| %>
    <li><%= car.brand %></li>
    <li><%= car.model %></li>
    <li><%= car.owner.nickname %></li>
    <%= link_to "More details", car_path(car) %>
  <% end %>
</ul>

app/views/cars/show.html.erb
<h1>This is my page for <%= @car.brand %></h1>

<ul>
  <li><%= @car.model %></li>
  <li><%= @car.year %></li>
  <li><%= @car.fuel %></li>
</ul>

<%= simple_form_for [@car, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit %>
<% end %>

<% if @car.favourites.empty? %>
  <%= simple_form_for [@car, @favourite] do |f| %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
<% else %>
  <p class="btn btn-warning">car in your garage</p>
<% end %>




<h3><%= "Here are the reviews:" %></h3>
<ul>
<% @car.reviews.each do |review| %>
<li><%= review.comment %></li>
<li><%= "#{review.rating} *" %></li>
<% end %>
</ul>

app/views/favourites/index.html.erb
<h1>this is your garage!</h1>

<ul>
<% @favourites.each do |favourite| %>
<li><%= favourite.car.brand %></li>
<li><%= favourite.car.model %></li>
<%= link_to "delete", favourite_path(favourite), data:
  { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "font-white btn btn-primary" %>
<% end %>
</ul>

<%= link_to 'back to all cars', cars_path(@car) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Awesome Garage" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "cars_path", class: "navbar-logo" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Showroom", cars_path(@cars), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Favourites", favourites_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: url(<%= asset_path 'banner.jpg' %>)">
  <div class="text-start">
    <h1>Gone In 60 Seconds</h1>
  </div>
</div>

<div class= "background-home">
  <p>Welcome to the garage of Gone in 60 Seconds. Our lead engineer Nicholas Cage has stollen 50 luxury vehicles in one
  night in order to save the life of his brother, who has fallen foul of a dangerous crime lord. Once the most successful
  car thief in California, he has reassembled his old gang to fulfil the almost impossible mission. This website is dedicated
  to selling his stolen cars to pay off his brother's debt.  Happy browsing! However don't take too long as they may be gone
  within a few seconds or indeed 60...
  </p>

</div>